### ISSUE TITLE
Meta2 fall broken during container creation/deletion

### ISSUE THREAD

**Issue by sebastienlapierre** [open-io/oio-sds#1004]
release: 4.0.0.a3
During container create and delete action,  meta2 fall broken.
Here is the trace:
```
Thread 19 (Thread 0x7fffc1ffb700 (LWP 36362)):
#0  0x00007ffff436a1d7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff436b8c8 in __GI_abort () at abort.c:90
#2  0x00007ffff43a9f07 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff44b4b48 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/unix/sysv/linux/libc_fatal.c:196
#3  0x00007ffff43afda4 in malloc_printerr (action=<optimized out>, str=0x7ffff44b4b70 "munmap_chunk(): invalid pointer", ptr=<optimized out>,
    ar_ptr=<optimized out>) at malloc.c:5013
#4  0x00007ffff6c7541e in g_free () from /lib64/libglib-2.0.so.0
#5  0x00007ffff6c8e459 in g_strfreev () from /lib64/libglib-2.0.so.0
#6  0x00007ffff634c074 in filter_services_and_clean (type=0x7fffc1ffa930 "meta2", src=0x7fff9c037720, ss=0x7ffff654f7c0 <SRV>)
    at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/sqlx/sqlx_service.c:423
#7  _get_peers_wrapper (ss=0x7ffff654f7c0 <SRV>, name=0x7fffc1ffa7d0, nocache=1, result=0x7fffc1ffa730)
```
And:
 ```
Thread 19 (Thread 0x7fffc1ffb700 (LWP 36362)):
#0  0x00007ffff436a1d7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff436b8c8 in __GI_abort () at abort.c:90
#2  0x00007ffff43a9f07 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff44b4b48 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/unix/sysv/linux/libc_fatal.c:196
#3  0x00007ffff43afda4 in malloc_printerr (action=<optimized out>, str=0x7ffff44b4b70 "munmap_chunk(): invalid pointer", ptr=<optimized out>,
    ar_ptr=<optimized out>) at malloc.c:5013
#4  0x00007ffff6c7541e in g_free () from /lib64/libglib-2.0.so.0
#5  0x00007ffff6c8e459 in g_strfreev () from /lib64/libglib-2.0.so.0
#6  0x00007ffff634c074 in filter_services_and_clean (type=0x7fffc1ffa930 "meta2", src=0x7fff9c037720, ss=0x7ffff654f7c0 <SRV>)
    at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/sqlx/sqlx_service.c:423
#7  _get_peers_wrapper (ss=0x7ffff654f7c0 <SRV>, name=0x7fffc1ffa7d0, nocache=1, result=0x7fffc1ffa730)
---Type <return> to continue, or q <return> to quit---
    at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/sqlx/sqlx_service.c:494
#8  0x00007ffff5ca60c5 in _election_get_peers (manager=<optimized out>, n=0x7fffc1ffa7d0, nocache=<optimized out>, result=0x7fffc1ffa768)
    at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/sqliterepo/election.c:655
#9  0x00007ffff5ca6eeb in election_has_peers (m=m@entry=0x623ba0, n=n@entry=0x7fffc1ffa7d0, nocache=nocache@entry=0, result=result@entry=0x7fffc1ffa784)
    at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/sqliterepo/election.c:569
#10 0x00007ffff5ca858d in _election_make (m=0x623ba0, n=0x7fffc1ffa7d0, op=ELOP_START)
    at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/sqliterepo/election.c:1702
#11 0x00007ffff5caadd0 in _handler_GETVERS (reply=0x7fffc1ffa9e0, repo=0x623d90, ignored=<optimized out>)
    at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/sqliterepo/replication_dispatcher.c:1346
#12 0x00007ffff736cad6 in _client_call_handler () at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/server/transport_gridd.c:698
#13 _client_manage_l4v (client=client@entry=0x7fffd4006330, gba=<optimized out>, gba=<optimized out>)
    at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/server/transport_gridd.c:790
#14 0x00007ffff736cecc in transport_gridd_notify_input (clt=0x7fffd4006330)
    at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/server/transport_gridd.c:481
#15 0x00007ffff7369585 in _client_manage_input () at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/server/network_server.c:1333
#16 _client_manage_event (events=<optimized out>, clt=0x7fffd4006330)
    at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/server/network_server.c:1403
#17 _cb_tcp_worker (clt=0x7fffd4006330, srv=0x61f2a0) at /usr/src/debug/oio-sds-78a9a0137dc043e544abc5375e42ca9df76cf633/server/network_server.c:1147
#18 0x00007ffff6c95a7c in g_thread_pool_thread_proxy () from /lib64/libglib-2.0.so.0
#19 0x00007ffff6c950f5 in g_thread_proxy () from /lib64/libglib-2.0.so.0
#20 0x00007ffff4120dc5 in start_thread (arg=0x7fffc1ffb700) at pthread_create.c:308
#21 0x00007ffff442c73d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by fvennetier** [comment]
Fixed by #1003
