### ISSUE TITLE
oio-indexer raise an exception on missing xattr grid.content.container

### ISSUE THREAD

**Issue by murlock** [open-io/oio-sds#1055]
Running rdir functional tests triggers an exception in oio-indexer:

```
$ oio-reset.sh -f etc/bootstrap-preset-SINGLE.yml
$ nosetests -v 
tests.functional.rdir.test_client.TestRdirClient.test_fetch_multi_req ... ok
tests.functional.rdir.test_client.TestRdirClient.test_fetch_one_req_post ... ok
tests.functional.rdir.test_indexer.TestIndexerCrawler.test_index_chunk ... ok
tests.functional.rdir.test_indexer.TestIndexerCrawler.test_index_chunk_missing_xattr ... ok
tests.functional.rdir.test_indexer.TestIndexerCrawler.test_index_unicode_chunk ... ok
tests.functional.rdir.test_server.TestRdirServer.test_explicit_create ... ok
tests.functional.rdir.test_server.TestRdirServer.test_implicit_create ... ok
tests.functional.rdir.test_server.TestRdirServer.test_lock_unlock ... ok
tests.functional.rdir.test_server.TestRdirServer.test_push_missing_fields ... ok
tests.functional.rdir.test_server.TestRdirServer.test_rdir_clear_and_lock ... ok
tests.functional.rdir.test_server.TestRdirServer.test_vol_status ... ok
tests.functional.rdir.test_server.TestRdirServer2.test_explicit_create ... ok
tests.functional.rdir.test_server.TestRdirServer2.test_implicit_create ... ok
tests.functional.rdir.test_server.TestRdirServer2.test_lock_unlock ... ok
tests.functional.rdir.test_server.TestRdirServer2.test_push_missing_fields ... ok
tests.functional.rdir.test_server.TestRdirServer2.test_rdir_clear_and_lock ... ok
tests.functional.rdir.test_server.TestRdirServer2.test_status ... ok
tests.functional.rdir.test_server.TestRdirServer2.test_vol_status ... ok

----------------------------------------------------------------------
Ran 18 tests in 17.686s

OK
```

```
$ journalctl -f
juin 27 11:37:30 asus OIO,OPENIO,rdir,1[10545]: 10545 9F5A access INF 127.0.0.1:5999 127.0.0.1:57464 POST 201 10172 0 - - /v1/rdir/create?vol=C7BC327D t=10114
juin 27 11:37:30 asus OIO,OPENIO,rdir,1[10545]: 10545 9F5A access INF 127.0.0.1:5999 127.0.0.1:57464 GET 200 73 36 - - /v1/rdir/status?vol=C7BC327D t=44
juin 27 11:37:30 asus OIO,OPENIO,proxy[9919]: 9919 CE64 log INF oio.proxy old-style flush
juin 27 11:37:30 asus OIO,OPENIO,cs,1[9900]: 9900 0ACE log NOT oio.cluster.module [NS=OPENIO][SRVTYPE=echo] flush done!
juin 27 11:37:30 asus OIO,OPENIO,proxy[9919]: 9919 CE64 access INF 127.0.0.1:6000 127.0.0.1:57908 POST 200 333 29 - - /v3.0/OPENIO/conscience/deregister?type=echo t=270
juin 27 11:37:30 asus OIO,OPENIO,cs,1[9900]: 9900 35FE log NOT oio.cluster.module [NS=OPENIO][SRVTYPE=echo] flush done!
juin 27 11:37:30 asus OIO,OPENIO,proxy[9919]: 9919 6924 access INF 127.0.0.1:6000 127.0.0.1:57908 POST 200 366 29 - - /v3.0/OPENIO/conscience/flush?type=echo t=299
juin 27 11:37:37 asus OIO,OPENIO,indexer,2[9923]: 9923 7F07BD4F6C30 log INFO started=2017-06-27T11:37:37 elapsed=0.00 pass=3 errors=0 chunks=0 0.00/s
juin 27 11:37:37 asus OIO,OPENIO,indexer,2[9923]: 9923 7F07BD4F6C30 log INFO ended=2017-06-27T11:37:37 elapsed=0.00 pass=3 errors=0 chunks=0 0.00/s
juin 27 11:37:37 asus OIO,OPENIO,meta0,1[9930]: 9930 CA03 access INF 127.0.0.1:6005 127.0.0.1:40168 M0_ALL 200 390 131176 - C926466D1E6AB198510599E81F0C114B t=322
juin 27 11:37:43 asus OIO,OPENIO,indexer,3[9921]: 9921 7F47A6908C30 log INFO started=2017-06-27T11:37:43 elapsed=0.00 pass=3 errors=0 chunks=0 0.00/s
juin 27 11:37:43 asus OIO,OPENIO,indexer,3[9921]: 9921 7F47A6908C30 log INFO ended=2017-06-27T11:37:43 elapsed=0.00 pass=3 errors=0 chunks=0 0.00/s
juin 27 11:37:44 asus OIO,OPENIO,indexer,1[9925]: 9925 7F077B48EC30 log INFO started=2017-06-27T11:37:44 elapsed=0.00 pass=3 errors=0 chunks=0 0.00/s
juin 27 11:37:44 asus OIO,OPENIO,indexer,1[9925]: 9925 7F077B48EC30 log ERROR ERROR while updating /home/murlock/.oio/sds/data/OPENIO-rawx-1/80F/80F0A4A566CA83CB419890A699B84C6E56F98700754E2765E6E0C595EEF9A63B
                                                  Traceback (most recent call last):
                                                    File "/home/murlock/openio/oio-sds/oio/blob/indexer.py", line 39, in safe_update_index
                                                      self.update_index(path)
                                                    File "/home/murlock/openio/oio-sds/oio/blob/indexer.py", line 92, in update_index
                                                      'Missing extended attribute %s' % e)
                                                  FaultyChunk: Missing extended attribute grid.content.container
juin 27 11:37:44 asus OIO,OPENIO,meta0,1[9930]: 9930 16AB access INF 127.0.0.1:6005 127.0.0.1:40878 M0_GET 200 280 91 - BF26F5DA76FB8B16891E8D8E12F488D1 t=169 5979
juin 27 11:37:44 asus OIO,OPENIO,meta1,1[9929]: 9929 3896 access INF 127.0.0.1:6006 127.0.0.1:59762 M1_LIST 200 1374 95 5979D39C9E1035CECBB5C559D34018ECDDE2C1D0B4F1C672BF25BC625B5A2320 BF26F5DA76FB8B16891E8D8E12F488D1 t=1295 OPENIO/_RDIR/127.0.0.1%3A6009/rdir|5979D39C9E1035CECBB5C559D34018ECDDE2C1D0B4F1C672BF25BC625B5A2320|rdir
juin 27 11:37:44 asus OIO,OPENIO,meta0,1[9930]: 9930 16AB access INF 127.0.0.1:6005 127.0.0.1:40890 M0_GET 200 164 91 - BF26F5DA76FB8B16891E8D8E12F488D1 t=116 5979
juin 27 11:37:44 asus OIO,OPENIO,proxy[9919]: 9919 CE64 access INF 127.0.0.1:6000 127.0.0.1:59430 GET 200 8114 193 5979D39C9E1035CECBB5C559D34018ECDDE2C1D0B4F1C672BF25BC625B5A2320 - /v3.0/OPENIO/reference/show?acct=_RDIR&ref=127.0.0.1%3A6009&type=rdir t=7967
juin 27 11:37:44 asus OIO,OPENIO,indexer,1[9925]: 9925 7F077B48EC30 log INFO ended=2017-06-27T11:37:44 elapsed=0.04 pass=3 errors=1 chunks=3 69.27/s
```

**Comment by kamel-rahim** [comment]
This is caused by a test where we removed the attribute grid.content.container xattr to a chunk.
The chunk is not deleted.
