### ISSUE TITLE
event-agent: connection aborted to oio-proxy

### ISSUE THREAD

**Issue by jkasarherou** [open-io/oio-sds#1060]
this is the stack trace you can find in the logs:

```
oio-event-agent,0: err 10522 28FC190 log ERROR handling event 1691365 (bury)#012Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/oio/event/consumer.py", line 203, in handle
self.process_event(job_id, event, beanstalk)
File "/usr/lib/python2.7/site-packages/oio/event/consumer.py", line 226, in process_event
handler(event, cb)
File "/usr/lib/python2.7/site-packages/oio/event/filters/base.py", line 18, in __call__
self.process(env, cb)
File "/usr/lib/python2.7/site-packages/oio/event/filters/account_update.py", line 39, in process
p = urlparse('http://' + self.app.app.acct_addr)
File "/usr/lib/python2.7/site-packages/oio/event/consumer.py", line 234, in acct_addr
acct_instance = self.cs.next_instance(ACCOUNT_SERVICE)
File "/usr/lib/python2.7/site-packages/oio/conscience/client.py", line 33, in next_instance
return self.next_instances(pool, size=1)[0]
File "/usr/lib/python2.7/site-packages/oio/conscience/client.py", line 24, in next_instances
resp, body = self._request('GET', uri, params=params)
File "/usr/lib/python2.7/site-packages/oio/common/client.py", line 51, in _request
return self._direct_request(method, url, **kwargs)
File "/usr/lib/python2.7/site-packages/oio/common/client.py", line 37, in _direct_request
**kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

I suspect this could be caused by a oio-proxy dropping connections (segfault?).

**Comment by fvennetier** [comment]
With c08a9e531dd0f41d169d2217eb8c416690d391e9 I changed the way the `AccountClient` gets the account service address. If it cannot refresh the address, it will continue with the old one.

**Comment by jfsmig** [comment]
Could not reproduce in an acceptable delay.
