### ISSUE TITLE
[oio-blob-rebuilder] Error at the end of oio-blob-rebuilder

### ISSUE THREAD

**Issue by sebastienlapierre** [open-io/oio-sds#1170]
openio-sds version: 4.1.0

Even if the `oio-blob-rebuilder` has passed well, I have the following message at the end.

Incident date on rawx service:
```
[root@relex01 ~]# openio volume admin show  10.0.1.19:6201 --oio-ns OPENIO
+---------------------+----------------+
| Field               | Value          |
+---------------------+----------------+
| volume              | 10.0.1.19:6201 |
| admin|incident_date | 1505405282     |
+---------------------+----------------+
```
cmd:
```
oio-blob-rebuilder OPENIO  --volume 10.0.1.19:6201 --log-level DEBUG --chunks-per-second 2
```
error: 
```
6788 15D42D0 log DEBUG copy chunk from http://10.0.1.20:6201/455463E72FD90F094A254C27B654291DD4D4A6A2420A76070198CFFA3B8BA600 to http://10.0.1.19:6202/2C9F7F13E4FD905672ED0D13C691559E2D64F14BEEF0ECDB99B5EC5BF44E2CC9
6788 15D42D0 log ERROR ERROR in rebuilder: Invalid incident date for [10.0.1.19:6201] (HTTP 500) (STATUS 500)
Traceback (most recent call last):
  File "/usr/bin/oio-blob-rebuilder", line 100, in <module>
    worker.rebuilder_pass_with_lock()
  File "/usr/lib/python2.7/site-packages/oio/blob/rebuilder.py", line 118, in rebuilder_pass_with_lock
    self.rebuilder_pass()
  File "/usr/lib/python2.7/site-packages/oio/blob/rebuilder.py", line 129, in rebuilder_pass
    for container_id, content_id, chunk_id, _ in chunks:
  File "/usr/lib/python2.7/site-packages/oio/rdir/client.py", line 259, in chunk_fetch
    json=req_body)
  File "/usr/lib/python2.7/site-packages/oio/rdir/client.py", line 208, in _rdir_request
    resp, body = self._direct_request(method, uri, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/oio/api/base.py", line 153, in _direct_request
    raise exceptions.from_response(resp, body)
ClientException: Invalid incident date for [10.0.1.19:6201] (HTTP 500) (STATUS 500) 
```

**Comment by AymericDu** [comment]
#1172
