### ISSUE TITLE
Shorten the error messages in the `oio-event-agent` when no account service is present

### ISSUE THREAD

**Issue by jfsmig** [open-io/oio-sds#1326]
Currently, with the HEAD of 4.1.x (a.k.a. tag 4.1.12), when an event is buried because there is no account service available, a humongous backtrace is dumped in the log. This is useless, and even harmful because it spams the log collector.

```
Jan 16 10:54:20 jfs-lenovo OIO,OPENIO,event-agent[8825]: 8825 7F588671F370 log ERROR Burying event 380: {u'url': {u'account': u'_RDIR', u'ns': u'OPENIO', u'user': u'127.0.0.1:6024', u'id': u'4D9BCEC7B75DB5B08FA9A19C8468CE2B8B43A06811A646B77FC3AEE82EA46473'}, u'data': [{u'host': u'127.0.0.1:6026', u'args': u'', u'type': u'rdir', u'seq': 1}], u'when': 1516096460582254, u'event': u'account.services', 'job_id': '380'}
  Traceback (most recent call last):
  File "/home/jfs/public_git/github.com/jfsmig/oio-sds/oio/event/consumer.py", line 226, in handle
    self.process_event(job_id, event, beanstalk)
  File "/home/jfs/public_git/github.com/jfsmig/oio-sds/oio/event/consumer.py", line 254, in process_event
    handler(event, cb)
  File "/home/jfs/public_git/github.com/jfsmig/oio-sds/oio/event/filters/base.py", line 35, in __call__
    self.process(env, cb)
  File "/home/jfs/public_git/github.com/jfsmig/oio-sds/oio/event/filters/account_update.py", line 79, in process
    url.get('account'), read_timeout=ACCOUNT_TIMEOUT)
  File "/home/jfs/public_git/github.com/jfsmig/oio-sds/oio/account/client.py", line 113, in account_create
    resp, _body = self.account_request(account, 'PUT', 'create', **kwargs)
  File "/home/jfs/public_git/github.com/jfsmig/oio-sds/oio/account/client.py", line 86, in account_request
    self._maybe_refresh_endpoint()
  File "/home/jfs/public_git/github.com/jfsmig/oio-sds/oio/account/client.py", line 71, in _maybe_refresh_endpoint
    self._refresh_endpoint(now)
  File "/home/jfs/public_git/github.com/jfsmig/oio-sds/oio/account/client.py", line 59, in _refresh_endpoint
    addr = self._get_account_addr()
  File "/home/jfs/public_git/github.com/jfsmig/oio-sds/oio/account/client.py", line 54, in _get_account_addr
    raise ClientException("No Account service found")
ClientException: n/a (HTTP No Account service found)
```

**Comment by jfsmig** [comment]
Fixed in #1327
