### ISSUE TITLE
oio-account-server is too verbose when an exception is raised

### ISSUE THREAD

**Issue by jfsmig** [open-io/oio-sds#165]
Here is a sample output when I stop the redis server:

    Aug 31 23:59:29 localhost OIO,NS,account,1[18010]: Error handling request
                                                   Traceback (most recent call last):
                                                     File "/usr/lib/python2.7/site-packages/gunicorn/workers/async.py", line 47, in handle
                                                       self.handle_request(listener_name, req, client, addr)
                                                     File "/usr/lib/python2.7/site-packages/gunicorn/workers/async.py", line 100, in handle_request
                                                       respiter = self.wsgi(environ, resp.start_response)
                                                     File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
                                                       return self.wsgi_app(environ, start_response)
                                                     File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
                                                       response = self.make_response(self.handle_exception(e))
                                                     File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
                                                       reraise(exc_type, exc_value, tb)
                                                     File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
                                                       response = self.full_dispatch_request()
                                                     File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
                                                       rv = self.handle_user_exception(e)
                                                     File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
                                                       reraise(exc_type, exc_value, tb)
                                                     File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
                                                       rv = self.dispatch_request()
                                                     File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
                                                       return self.view_functions[rule.endpoint](**req.view_args)
                                                     File "/home/jfs/public_git/github.com/jfsmig/oio-sds/python/oio/account/server.py", line 40, in status
                                                       status = get_backend().status()
                                                     File "/home/jfs/public_git/github.com/jfsmig/oio-sds/python/oio/account/backend.py", line 299, in status
                                                       account_count = conn.hlen('accounts:')
                                                     File "/usr/lib/python2.7/site-packages/redis/client.py", line 1846, in hlen
                                                       return self.execute_command('HLEN', name)
                                                     File "/usr/lib/python2.7/site-packages/redis/client.py", line 570, in execute_command
                                                       connection.send_command(*args)
                                                     File "/usr/lib/python2.7/site-packages/redis/connection.py", line 556, in send_command
                                                       self.send_packed_command(self.pack_command(*args))
                                                     File "/usr/lib/python2.7/site-packages/redis/connection.py", line 532, in send_packed_command
                                                       self.connect()
                                                     File "/usr/lib/python2.7/site-packages/redis/connection.py", line 436, in connect
                                                       raise ConnectionError(self._error_message(e))
                                                   ConnectionError: Error 111 connecting to 127.0.0.1:6379. ECONNREFUSED.

This is repeated once per second and completely fills the logs.

**Comment by jkasarherou** [comment]
This is convenient for debugging purposes, but I agree this should not stay like this.
