### ISSUE TITLE
Create object in OpenIO with backblaze config

### ISSUE THREAD

**Issue by han2291** [open-io/oio-sds#2036]
##### ISSUE TYPE

 - Bug Report
 - Documentation Report

##### COMPONENT NAME

OpenIO CLI 
Python API

##### SDS VERSION

```
Openio 7.0.0.0a3
```

##### CONFIGURATION

```
[default]
[OPENIO]
## ZK URL, at least used by zk-bootstrap.py
#zookeeper=127.0.0.1:2181
## Alternate ZK endpoints for specific services
#zookeeper.meta0=127.0.0.1:2181
#zookeeper.meta1=127.0.0.1:2181
#zookeeper.meta2=127.0.0.1:2181
#proxy-local=/home/han/.oio/sds/run/OPENIO-proxy.sock
proxy=127.0.0.1:6000
conscience=127.0.0.1:6003
ecd=127.0.0.1:6001
event-agent=beanstalk://127.0.0.1:6005
ns.meta1_digits=2
# Small pagination to avoid time-consuming tests
meta2.flush_limit=64
proxy.location=rack.127-0-0-1.6000
admin=127.0.0.1:6002
ns.storage_policy=BACKBLAZE
ns.chunk_size=1048576
proxy.cache.enabled=true

```

##### OS / ENVIRONMENT

```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

##### SUMMARY

hello, great software
I wonder if there is any guide or other form to init opnio with Backblaze? 
I want to use openio with backblaze backup, for this I configure it with the terminal file oio-reset.sh and I pass this as argument the file etc/bootstrap-preset-BACKBLAZE.yml which contains the following configuration:
```
storage_policy: "BACKBLAZE"
config:
   ns.chunk_size:1048576
redis:true
backblaze:
   bucket_name:
   account_id:
   application_key:
rawx:
   count: 3
```
OpenIO services are initialized correctly, however, when you want to create an object through the terminal with the command openio object create, the following exception appears

```
oio.common.exceptions.OioNetworkException: ('reqid=create-1DE054AAC41252BFD72DEAC7E,
host=127.0.0.1:6000', 'Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))
```
I even tried to create an object with Python API and throw me the same exception
Note: the file oio-reset.sh and bootstrap-preset-BACKBLAZE.yml were in the openio project and i put them my backblaze info account and bucket

##### STEPS TO REPRODUCE

From the Terminal I use the following commands
```bash
oio-sds/tools/oioreset.sh -f /etc/bootstrap-preset-BACKBLAZE.yml
openio account create my_account --oio-ns OPENIO
openio container create my_container --oio-ns OPENIO –oio-accunt my_account
openio object create my_container test.txt --oio-ns OPENIO –oio-account my_account
```

From my python code I use the following source code:
```
from oio import ObjectStorageApi
from oio import account
from oio import container
import oio

s = oio.api.object_storage.ObjectStorageApi("OPENIO")
ac = account.client.AccountClient({"namespace":"OPENIO"})
ACCOUNT = "my_account"
CONTAINER = "my_container"
ac.account_create(ACCOUNT)
s.container_create(ACCOUNT, CONTAINER)
s.object_create(ACCOUNT, CONTAINER, "test.txt")
```

##### ACTUAL RESULTS

From terminal with openio CLI throw me the following exception
```
Failed to upload test.txt in my_container: ('reqid=create-19BCE98896A748CA2DD13203A,
host=127.0.0.1:6000', 'Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))
+----------+------+------+--------+
| Name | Size | Hash | Status |
+----------+------+------+--------+
| test.txt | 0 | None | Failed |
+----------+------+------+--------+
Too many errors occured
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/cliff/app.py", line 400, in run_subcommand
result = cmd.run(parsed_args)
File "/home/han/.local/lib/python2.7/site-packages/oio/cli/__init__.py", line 156, in run
super(Lister, self).run(parsed_args)
File "/usr/lib/python2.7/dist-packages/cliff/display.py", line 116, in run
column_names, data = self.take_action(parsed_args)
File "/home/han/.local/lib/python2.7/site-packages/oio/cli/object/object.py", line 199, in take_action tls=parsed_args.tls)
Exception: Too many errors occured
Exception raised: Too many errors occured

```

In python throw me the following stacktrace exception
```
s.object_create(ACCOUNT, CONTAINER, "test.txt")
File "/home/han/.local/lib/python2.7/site-packages/oio/api/object_storage.py", line 665, in object_create self.object_create_ext(account, container, *args, **kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/common/decorators.py", line 86, in _wrapped return fnc(self, account, container, *args, **kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/common/decorators.py", line 126, in
_patch_kwargs return fnc(self, *args, **kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/common/decorators.py", line 28, in
ensure_headers_wrapper return func(*args, **kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/common/decorators.py", line 66, in
ensure_request_id_wrapper return func(*args, **kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/api/object_storage.py", line 780, in
object_create_ext key_file=key_file, append=append, **kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/api/object_storage.py", line 1374, in
_object_create **kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/api/object_storage.py", line 1333, in
_object_prepare policy=policy, **kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/api/io.py", line 775, in __init__
**kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/container/client.py", line 101, in
_reference_params cid=cid, params=params, **kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/container/client.py", line 720, in content_prepare 'POST', uri + '2', data=data, params=params, **kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/common/client.py", line 109, in _direct_request method, url, headers=headers, **kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/api/base.py", line 211, in _direct_request
url=url)
File "/home/han/.local/lib/python2.7/site-packages/oio/common/http_urllib3.py", line 112, in
oio_exception_from_httperror reraise(OioNetworkException, exc, extra)
File "/home/han/.local/lib/python2.7/site-packages/oio/common/exceptions.py", line 372, in reraise six_reraise(exc_type, exc_type(*args), exc_info()[2])
File "/home/han/.local/lib/python2.7/site-packages/oio/api/base.py", line 189, in _direct_request
resp = pool_manager.request(method, url, **out_kwargs)
File "/home/han/.local/lib/python2.7/site-packages/oio/common/http_urllib3.py", line 56, in request return super(SafePoolManager, self).request(*args, **kwargs2)
File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 70, in request
**urlopen_kw)
File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 148, in request_encode_body
return self.urlopen(method, url, **extra_kw)
File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 322, in urlopen
response = conn.urlopen(method, u.request_uri, **kw)
File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
_stacktrace=sys.exc_info()[2])
File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 367, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
chunked=chunked)
File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
httplib_response = conn.getresponse(buffering=True)
File "/usr/lib/python2.7/httplib.py", line 1161, in getresponse response.begin()
File "/usr/lib/python2.7/httplib.py", line 448, in begin version, status, reason = self._read_status()
File "/usr/lib/python2.7/httplib.py", line 412, in _read_status raise BadStatusLine("No status line received - the server has closed the connection")
oio.common.exceptions.OioNetworkException: ('reqid=create-1DE054AAC41252BFD72DEAC7E,
host=127.0.0.1:6000', 'Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))

```

**Comment by fvennetier** [comment]
Hello. I'm sorry to tell you that the Backblaze integration is no more supported. It has been removed from the master branch #2080.
