### ISSUE TITLE
meta2 test converter: segfault

### ISSUE THREAD

**Issue by jkasarherou** [open-io/oio-sds#228]
segfault while running `test_meta2_type_converter`

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `./test_meta2_type_converter'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f02beab35f8 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f02beab35f8 in raise () from /usr/lib/libc.so.6
#1  0x00007f02beab4a7a in abort () from /usr/lib/libc.so.6
#2  0x00007f02c20288c5 in g_assertion_message () from /usr/lib/libglib-2.0.so.0
#3  0x00007f02c202910e in g_assertion_message_error () from /usr/lib/libglib-2.0.so.0
#4  0x000000000040254a in _repo_wraper (ns=0x402c60 "NS", fr=0x7fff367d2738)
    at /home/noone/public_git/github.com/jkasarherou/oio-sds/meta2v2/test_meta2_type_converter.c:174
#5  0x00000000004027e7 in _container_wraper (cf=0x7fff367d2760)
    at /home/noone/public_git/github.com/jkasarherou/oio-sds/meta2v2/test_meta2_type_converter.c:215
#6  0x0000000000402866 in test_beans_to_raw_content () at /home/noone/public_git/github.com/jkasarherou/oio-sds/meta2v2/test_meta2_type_converter.c:227
#7  0x00007f02c202833b in ?? () from /usr/lib/libglib-2.0.so.0
#8  0x00007f02c2028503 in ?? () from /usr/lib/libglib-2.0.so.0
#9  0x00007f02c2028503 in ?? () from /usr/lib/libglib-2.0.so.0
#10 0x00007f02c202870e in g_test_run_suite () from /usr/lib/libglib-2.0.so.0
#11 0x00007f02c2028731 in g_test_run () from /usr/lib/libglib-2.0.so.0
#12 0x0000000000402a0c in main (argc=1, argv=0x7fff367d2b28) at /home/noone/public_git/github.com/jkasarherou/oio-sds/meta2v2/test_meta2_type_converter.c:277
```

**Comment by jfsmig** [comment]
The type converter is destined to be removed with the support of old-stylish meta2 structures, currently only required by old client.
You can safely inhibit the test.

**Comment by jkasarherou** [comment]
test removed in #232
