### ISSUE TITLE
Make "openio create" followed by "openio locate" work as expected

### ISSUE THREAD

**Issue by jfsmig** [open-io/oio-sds#800]
```
### 0 /home/jfs/public_git/github.com/jfsmig/oio-sds
(oio)jfs@jfs-lenovo 14 # openio container create JFS
+------+---------+
| Name | Created |
+------+---------+
| JFS  | True    |
+------+---------+


### 0 /home/jfs/public_git/github.com/jfsmig/oio-sds
(oio)jfs@jfs-lenovo 15 # openio --debug -v container locate JFS
Starting new HTTP connection (1): 127.0.0.1
"GET /v3.0/OPENIO/container/show?acct=ACCT&ref=JFS HTTP/1.1" 200 17
Starting new HTTP connection (1): 127.0.0.1
"GET /v3.0/OPENIO/reference/show?acct=ACCT&ref=JFS HTTP/1.1" 200 194
'system'
Traceback (most recent call last):
  File "/home/jfs/.local/python/oio/local/lib/python2.7/site-packages/cliff/app.py", line 387, in run_subcommand
    result = cmd.run(parsed_args)
  File "/home/jfs/.local/python/oio/local/lib/python2.7/site-packages/cliff/display.py", line 100, in run
    column_names, data = self.take_action(parsed_args)
  File "/home/jfs/public_git/github.com/jfsmig/oio-sds/oio/cli/storage/container.py", line 361, in take_action
    info = {'account': data['system']['sys.account'],
KeyError: 'system'
Exception raised: 'system'
```

**Comment by jfsmig** [comment]
Spotted thanks to @RaymondPo
