### ISSUE TITLE
ConnectionError on bootstrapping when rawx are not started

### ISSUE THREAD

**Issue by racciari** [open-io/oio-sds#828]
When bootstrapping a namespace and rawx are not started, I had this error:

```
# openio --oio-ns=VCFR1 directory bootstrap --replicas 3 -v --debug
Starting new HTTP connection (1): 172.17.25.5
"GET /v3.0/VCFR1/conscience/list?type=meta1 HTTP/1.1" 200 376
Computing meta1 prefix mapping...
0%
10%
20%
30%
40%
50%
60%
70%
80%
90%
100%
Equilibrating...
META1 Digits = 4
Replicas = 3
Scored positively = 3
Ideal number of prefixes per meta1: 65536
Rebalance moved 0 prefixes
Saving...
Starting new HTTP connection (1): 172.17.25.5
"POST /v3.0/VCFR1/admin/meta0_force HTTP/1.1" 204 0
Assigning rdir services to rawx services...
Starting new HTTP connection (1): 172.17.25.5
"GET /v3.0/VCFR1/conscience/list?type=rawx HTTP/1.1" 200 256
"GET /v3.0/VCFR1/conscience/list?full=1&type=rdir HTTP/1.1" 200 642
Starting new HTTP connection (1): 172.17.25.5
"GET /v3.0/VCFR1/reference/show?acct=_RDIR&ref=172.17.25.7%3A6004&type=rdir HTTP/1.1" 404 59
('Connection aborted.', BadStatusLine("''",))
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cliff/app.py", line 374, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/lib/python2.7/dist-packages/cliff/command.py", line 54, in run
    self.take_action(parsed_args)
  File "/usr/lib/python2.7/dist-packages/oio/cli/admin/directory.py", line 60, in take_action
    self.app.client_manager.admin.volume.assign_all_rawx()
  File "/usr/lib/python2.7/dist-packages/oio/rdir/client.py", line 38, in assign_all_rawx
    rdir = self._smart_link_rdir(rawx['addr'], cs, all_rdir)
  File "/usr/lib/python2.7/dist-packages/oio/rdir/client.py", line 68, in _smart_link_rdir
    polled = cs.poll('rdir', avoid=avoids, known=known)[0]
  File "/usr/lib/python2.7/dist-packages/oio/conscience/client.py", line 47, in poll
    data=json.dumps(ibody))
  File "/usr/lib/python2.7/dist-packages/oio/common/client.py", line 51, in _request
    return self._direct_request(method, url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/oio/common/client.py", line 37, in _direct_request
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
Exception raised: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by jkasarherou** [comment]
Looks like the proxy just crashed

**Comment by fvennetier** [comment]
It is actually due to a proxy crash.
```
#0  0x00007faa4585b5af in raise () from /lib64/libc.so.6
#1  0x00007faa4585c9aa in abort () from /lib64/libc.so.6
#2  0x00007faa47390395 in g_assertion_message (domain=domain@entry=0x7faa45bd62ca "oio.core", file=file@entry=0x7faa45bd6298 "/home/fvennetier/src/public_git/oio-sds/core/lb.c", line=line@entry=858, func=func@entry=0x7faa45bd6af0 <__func__.11263> "_search_first_at_location", message=message@entry=0x7faa38002ad0 "assertion failed: (start < tab->len)") at gtestutils.c:2432
#3  0x00007faa4739042a in g_assertion_message_expr (domain=0x7faa45bd62ca "oio.core", file=0x7faa45bd6298 "/home/fvennetier/src/public_git/oio-sds/core/lb.c", line=858, func=0x7faa45bd6af0 <__func__.11263> "_search_first_at_location", expr=<optimized out>) at gtestutils.c:2455
#4  0x00007faa45bd4cf4 in _search_first_at_location (tab=0x7faa18003b60, needle=17172078867512076937, start=0, end=4294967295) at /home/fvennetier/src/public_git/oio-sds/core/lb.c:858
#5  0x00007faa45bd3ae0 in _local_target__is_satisfied (lb=0x7faa18004790, target=0x7faa18002b90 "rawx", ctx=0x7faa41a955c0) at /home/fvennetier/src/public_git/oio-sds/core/lb.c:493
#6  0x00007faa45bd3dcb in _local__patch (self=0x7faa18004790, avoids=0x7faa38002a50, known=0x7faa38002a70, on_id=0x7faa41a956d8) at /home/fvennetier/src/public_git/oio-sds/core/lb.c:546
#7  0x00007faa45bd2c5e in oio_lb_pool__patch (self=0x7faa18004790, avoids=0x7faa38002a50, known=0x7faa38002a70, on_id=0x7faa41a956d8) at /home/fvennetier/src/public_git/oio-sds/core/lb.c:83
#8  0x00007faa45bd56cd in oio_lb__patch_with_pool (lb=0x1642650, name=0x7faa380029f0 "rdir", avoids=0x7faa38002a50, known=0x7faa38002a70, on_id=0x7faa41a956d8) at /home/fvennetier/src/public_git/oio-sds/core/lb.c:1058
#9  0x00000000004153f0 in _poll (args=0x7faa41a95880, body=0x7faa38001c20) at /home/fvennetier/src/public_git/oio-sds/proxy/lb_actions.c:202
#10 0x0000000000410a73 in rest_action (args=0x7faa41a95880, handler=0x415050 <_poll>) at /home/fvennetier/src/public_git/oio-sds/proxy/common.c:149
#11 0x00000000004155c4 in action_lb_poll (args=0x7faa41a95880) at /home/fvennetier/src/public_git/oio-sds/proxy/lb_actions.c:232
#12 0x000000000040d9de in handler_action (rq=0x7faa1c006bd0, rp=0x7faa41a95a60) at /home/fvennetier/src/public_git/oio-sds/proxy/metacd_http.c:257
#13 0x00000000004217e9 in http_manage_request () at /home/fvennetier/src/public_git/oio-sds/proxy/transport_http.c:536
#14 0x00000000004221ab in http_notify_input (clt=0x7faa3401b640) at /home/fvennetier/src/public_git/oio-sds/proxy/transport_http.c:623
#15 0x00007faa48885ae6 in _notify () at /home/fvennetier/src/public_git/oio-sds/server/network_server.c:1287
#16 0x00007faa48885c2c in _client_manage_input () at /home/fvennetier/src/public_git/oio-sds/server/network_server.c:1311
#17 0x00007faa48885deb in _client_manage_event (clt=0x7faa3401b640, events=1) at /home/fvennetier/src/public_git/oio-sds/server/network_server.c:1381
#18 0x00007faa4888533f in _cb_worker (clt=0x7faa3401b640, srv=0x164a960) at /home/fvennetier/src/public_git/oio-sds/server/network_server.c:1125
#19 0x00007faa47391bbe in g_thread_pool_thread_proxy (data=<optimized out>) at gthreadpool.c:307
#20 0x00007faa473911c5 in g_thread_proxy (data=0x1640680) at gthread.c:784
#21 0x00007faa4540d454 in start_thread () from /lib64/libpthread.so.0
#22 0x00007faa4591037f in clone () from /lib64/libc.so.6
```

The assertion `start < tab->len` is not verified.
```
/* return the position of the first item with the same location as the
 * value of <needle> */
static guint
_search_first_at_location (GArray *tab, const oio_location_t needle,
		const guint start, const guint end)
{
	EXTRA_ASSERT (start < tab->len);
	EXTRA_ASSERT (end < tab->len);

	if (start == end) {
		/* not found ? */
		if (needle != _location_at_position (tab, start))
			return (guint)-1;
		return _slide_to_first_at_location (tab, needle, start);
	}
```
