### ISSUE TITLE
oio-event-agent: does not start if some event handlers are missing from configuration

### ISSUE THREAD

**Issue by fvennetier** [open-io/oio-sds#882]
```
Traceback (most recent call last):
  File "/home/fvennetier/src/public_git/oio-sds/oio/event/agent.py", line 166, in spawn_worker
    worker.init()
  File "/home/fvennetier/src/public_git/oio-sds/oio/event/consumer.py", line 144, in init
    app=self)
  File "/home/fvennetier/src/public_git/oio-sds/oio/event/loader.py", line 72, in loadhandlers
    for name in names
  File "/home/fvennetier/src/public_git/oio-sds/oio/event/loader.py", line 72, in <genexpr>
    for name in names
  File "/home/fvennetier/src/public_git/oio-sds/oio/event/loader.py", line 78, in loadhandler
    context = loader.get_context(HANDLER, name, global_conf)
  File "/home/fvennetier/src/public_git/oio-sds/oio/event/loader.py", line 137, in get_context
    obj_type, name=name)
  File "/home/fvennetier/src/public_git/oio-sds/oio/event/loader.py", line 206, in find_config_section
    'No section %r found in config %r' % (name, self.filename))
LookupError: No section 'account.services' found in config '/home/fvennetier/.oio/sds/conf/event-handlers.conf'
```

Two solutions:
* Load a `noop` if no event handler configured
* Iterate on sections of the configuration file instead of a hardcoded list of events in oio/event/consumer.py

**Comment by jkasarherou** [comment]
I think loading a noop by default can be dangerous

**Comment by jkasarherou** [comment]
because noop is actually drop
