### ISSUE TITLE
Directory bootstrap failure on lowend servers

### ISSUE THREAD

**Issue by racciari** [open-io/oio-sds#903]
When bootstrapping a lowend server like a RaspberryPi, it ends with a HTTP500 failure:

```
root@raspberrypi:/home/pi# openio --oio-ns=OPENIO directory bootstrap --no-rdir -vvv --debug
admin API: cmd group openio.admin
directory API: cmd group openio.directory
storage API: cmd group openio.storage
command: directory bootstrap -> oio.cli.admin.directory.DirectoryInit
take_action(Namespace(rdir=False, replicas=3))
Using parameters {'admin_mode': False, 'log_level': 'DEBUG', 'is_cli': True, 'namespace': 'OPENIO', 'proxyd_url': 'http://192.168.1.49:6006', 'account_name': ''}
Starting new HTTP connection (1): 192.168.1.49
"GET /v3.0/OPENIO/conscience/list?type=meta1 HTTP/1.1" 200 132
Computing meta1 prefix mapping...
0%
10%
20%
30%
40%
50%
60%
70%
80%
90%
100%
Equilibrating...
No equilibration possible when meta1_digits is set to 0
Saving...
Starting new HTTP connection (1): 192.168.1.49
"POST /v3.0/OPENIO/admin/meta0_force HTTP/1.1" 500 32
Timeout (HTTP 500) (STATUS 7)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cliff/app.py", line 374, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/lib/python2.7/dist-packages/cliff/command.py", line 54, in run
    self.take_action(parsed_args)
  File "/usr/lib/python2.7/dist-packages/oio/cli/admin/directory.py", line 56, in take_action
    mapping.force()
  File "/usr/lib/python2.7/dist-packages/oio/directory/meta0.py", line 126, in force
    self.m0.force(self.to_json().strip())
  File "/usr/lib/python2.7/dist-packages/oio/directory/meta0.py", line 26, in force
    self._request('POST', uri, data=mapping)
  File "/usr/lib/python2.7/dist-packages/oio/common/client.py", line 51, in _request
    return self._direct_request(method, url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/oio/common/client.py", line 45, in _direct_request
    raise from_response(resp, body)
ClientException: Timeout (HTTP 500) (STATUS 7)
clean up DirectoryInit: Timeout (HTTP 500) (STATUS 7)
Exception raised: Timeout (HTTP 500) (STATUS 7)
```

**Comment by fvennetier** [comment]
Until 4.x versions, oio-proxy's internal timeout toward meta0 is set to 10 seconds. You can change it at compilation time with `cmake -DM0V2_CLIENT_TIMEOUT=30.0 [...]`. The timeout between the CLI and oio-proxy is already 30 seconds.

Starting from 4.x version, you change oio-proxy's internal timeout toward meta0 in `/etc/oio/sds.conf` with `meta0.outgoing.timeout.common.req=30s` (you need to restart the process).

**Comment by jfsmig** [comment]
Related to #857

**Comment by fvennetier** [comment]
We should make the timeout between the client and the proxy configurable.It is currently hardcoded to 30s [here](https://github.com/open-io/oio-sds/blob/4.1.2/oio/cli/admin/directory.py#L92).

**Comment by racciari** [comment]
Come on @kamel-rahim, save the day \o/

**Comment by jfsmig** [comment]
Improved in #1393, #1386, #1385, #1384, #1383, #1382, #1381, #1373,
