### ISSUE TITLE
Segmentation faults often appear during rawx restart

### ISSUE THREAD

**Issue by sebastienlapierre** [open-io/oio-sds#963]
When I restart a rawx, I often find an anormal  segfault error in dmesg:
```
[5290283.725527] httpd[24973]: segfault at 7f417d4a9ef0 ip 00007f417d4a9ef0 sp 00007ffdcaabf448 error 14 in libfreebl3.so[7f417d6b2000+2000]
```

The core generated is: 
```
gdb /usr/sbin/httpd /var/lib/oio/sds/SCALAIR/coredump/core.24973

GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/httpd...Reading symbols from /usr/lib/debug/usr/sbin/httpd.debug...done.
done.
[New LWP 24973]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

warning: the debug information found in "/usr/lib/debug//lib64/libpgm-5.2.so.0.0.122.debug" does not match "/lib64/libpgm-5.2.so.0" (CRC mismatch).


warning: the debug information found in "/usr/lib/debug/usr/lib64/libpgm-5.2.so.0.0.122.debug" does not match "/lib64/libpgm-5.2.so.0" (CRC mismatch).


warning: the debug information found in "/usr/lib/debug//usr/lib64/libpgm-5.2.so.0.0.122.debug" does not match "/lib64/libpgm-5.2.so.0" (CRC mismatch).


warning: the debug information found in "/usr/lib/debug/usr/lib64//libpgm-5.2.so.0.0.122.debug" does not match "/lib64/libpgm-5.2.so.0" (CRC mismatch).

Missing separate debuginfo for /lib64/libpgm-5.2.so.0
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/5b/bcf7aa1e320151765c522ca8b741aeaecdcdd6.debug
Core was generated by `/usr/sbin/httpd -D FOREGROUND -f /etc/oio/sds/SCALAIR/rawx-26/rawx-26-httpd.con'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f417d4a9ef0 in ?? ()
```

(gdb) bt
```
#0  0x00007f417d4a9ef0 in ?? ()
#1  0x00007f417f5e470e in ap_run_mpm_query (query_code=query_code@entry=2, result=result@entry=0x7ffdcaabf4ac, _rv=_rv@entry=0x7ffdcaabf484)
    at mpm_common.c:99
#2  0x00007f417f5e530e in ap_mpm_query (query_code=query_code@entry=2, result=result@entry=0x7ffdcaabf4ac) at mpm_common.c:414
#3  0x00007f417f602504 in log_tid (info=<optimized out>, arg=<optimized out>, buf=0x7ffdcaabf5ff "", buflen=8129) at log.c:606
#4  0x00007f417f60345c in do_errorlog_default (buflen=8192, args=0x7ffdcaac3640,
    errstr_fmt=0x7f417f621b18 "AH00060: seg fault or similar nasty error detected in the parent process", errstr_end=<synthetic pointer>,
    errstr_start=<synthetic pointer>, buf=0x7ffdcaabf5c0 "[Fri Apr 07 10:26:26.354889 2017] [core:notice] [pid 24973:tid ", info=0x7ffdcaabf570) at log.c:938
#5  log_error_core (file=0x7f417f621a04 "mpm_unix.c", line=869, module_index=0, level=<optimized out>, status=0, s=<optimized out>, c=<optimized out>,
    c@entry=0x0, r=r@entry=0x0, pool=pool@entry=0x0,
    fmt=fmt@entry=0x7f417f621b18 "AH00060: seg fault or similar nasty error detected in the parent process", args=args@entry=0x7ffdcaac3640) at log.c:1264
#6  0x00007f417f6038d8 in ap_log_error_ (file=file@entry=0x7f417f621a04 "mpm_unix.c", line=line@entry=869, module_index=module_index@entry=0,
    level=level@entry=5, status=status@entry=0, s=<optimized out>,
    fmt=fmt@entry=0x7f417f621b18 "AH00060: seg fault or similar nasty error detected in the parent process") at log.c:1298
#7  0x00007f417f60973a in sig_coredump (sig=11) at mpm_unix.c:866
#8  <signal handler called>
#9  0x00007f417d4aa020 in ?? ()
#10 <signal handler called>
#11 strcmp () at ../sysdeps/x86_64/strcmp.S:137
#12 0x00007f417f3ab374 in _dl_name_match_p (name=0x7f417e4e22e3 "libc.so.6", map=<optimized out>) at dl-misc.c:311
#13 0x00007f417f3a45f6 in do_lookup_x (new_hash=new_hash@entry=1842243024, old_hash=old_hash@entry=0x7ffdcaac43f0, result=result@entry=0x7ffdcaac4400,
    scope=<optimized out>, i=<optimized out>, i@entry=0, flags=flags@entry=1, skip=skip@entry=0x0, undef_map=undef_map@entry=0x7f417f5b0000)
    at dl-lookup.c:463
#14 0x00007f417f3a4e6f in _dl_lookup_symbol_x (undef_name=0x7f417e4d9dbc "__cxa_finalize", undef_map=0x7f417f5b0000, ref=ref@entry=0x7ffdcaac44b8,
    symbol_scope=0x7f417f5b0358, version=0x7f417f5aecb0, type_class=type_class@entry=1, flags=1, skip_map=skip_map@entry=0x0) at dl-lookup.c:739
#15 0x00007f417f3a9776 in _dl_fixup (l=<optimized out>, reloc_arg=<optimized out>) at ../elf/dl-runtime.c:113
#16 0x00007f417f3b0260 in _dl_runtime_resolve () at ../sysdeps/x86_64/dl-trampoline.S:87
#17 0x00007f417e4fb4c3 in __do_global_dtors_aux () from /lib64/libdb-5.3.so
#18 0x00007ffdcaac46a0 in ?? ()
#19 0x00007f417f3aaa1a in _dl_fini () at dl-fini.c:253
Backtrace stopped: frame did not save the PC
```

**Comment by fvennetier** [comment]
Unfortunately, this seems not related to oio-sds.

Maybe this article can help you track the issue further: http://blog.kavoori.com/2015-03-21/apache-crash-with-seg-fault.html.
